Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	compute_UNI
	1

[Wed Oct 14 15:53:20 2020]
rule compute_UNI:
    input: data/orthology_anophelinae.tsv
    output: results/UNI.tsv
    jobid: 0

[Wed Oct 14 15:53:20 2020]
Error in rule compute_UNI:
    jobid: 0
    output: results/UNI.tsv

RuleException:
CalledProcessError in line 9 of /home/lruzzant/evol-feat-snakemake/workflow/Snakefile:
Command 'set -euo pipefail;  /home/lruzzant/miniconda3/envs/evol-feat/bin/python3.7 /home/lruzzant/evol-feat-snakemake/workflow/.snakemake/scripts/tmpnwhnasyr.compute_UNI.py' returned non-zero exit status 1.
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/home/lruzzant/evol-feat-snakemake/workflow/Snakefile", line 9, in __rule_compute_UNI
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
Removing output files of failed job compute_UNI since they might be corrupted:
results/UNI.tsv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/lruzzant/evol-feat-snakemake/workflow/.snakemake/log/2020-10-14T155320.004881.snakemake.log
