Building DAG of jobs...
candidate job split_user_og_features
    wildcards: 
selected job split_user_og_features
    wildcards: 
file None:
    Producer found, hence exceptions are ignored.

Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	split_user_og_features
	1

[Mon Feb 15 13:10:07 2021]
rule split_user_og_features:
    jobid: 0

[Mon Feb 15 13:10:07 2021]
Error in rule split_user_og_features:
    jobid: 0

RuleException:
CalledProcessError in line 19 of /mnt/c/Users/livio/evol-feat-snakemake/workflow/Snakefile:
Command 'set -euo pipefail;  /home/lruzzant/miniconda3/envs/evol-feat/bin/python3.7 /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/scripts/tmpjy9a6co3.split_features.py' returned non-zero exit status 1.
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/mnt/c/Users/livio/evol-feat-snakemake/workflow/Snakefile", line 19, in __rule_split_user_og_features
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/log/2021-02-15T131007.568289.snakemake.log
