Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	compute_age
	1	compute_universality
	1	create_mrca_branchlengths_table
	1	create_orthology_dictionaries
	1	merge_features
	1	split_user_orthogroup_features
	7

[Mon Feb 15 18:29:56 2021]
checkpoint split_user_orthogroup_features:
    input: input/TEST_apoidea_og_feats.tsv.txt
    output: output/user_orthogroup_features/
    jobid: 2
Downstream jobs will be updated after completion.

Updating job 1 (merge_features).
[Mon Feb 15 18:29:58 2021]
Finished job 2.
1 of 7 steps (14%) done

[Mon Feb 15 18:29:58 2021]
rule create_orthology_dictionaries:
    input: input/apoidea_orthology.txt
    output: output/orthogroups.pickle, output/genes.pickle
    jobid: 5

[Mon Feb 15 18:29:59 2021]
Error in rule create_orthology_dictionaries:
    jobid: 5
    output: output/orthogroups.pickle, output/genes.pickle

RuleException:
CalledProcessError in line 8 of /mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/compute_features.smk:
Command 'set -euo pipefail;  /home/lruzzant/miniconda3/envs/evol-feat/bin/python3.7 /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/scripts/tmp1oev00v3.create_orthology_dictionaries.py' returned non-zero exit status 1.
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/compute_features.smk", line 8, in __rule_create_orthology_dictionaries
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
Removing output files of failed job create_orthology_dictionaries since they might be corrupted:
output/orthogroups.pickle, output/genes.pickle
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/log/2021-02-15T182956.042359.snakemake.log
