Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	compute_average_copy_number
	1	compute_universality
	1	merge_features
	1	split_user_orthogroup_features
	5

[Mon Feb 15 20:22:41 2021]
checkpoint split_user_orthogroup_features:
    input: input/user_features.txt
    output: output/user_orthogroup_features/
    jobid: 2
Downstream jobs will be updated after completion.

Updating job 1 (merge_features).
[Mon Feb 15 20:22:42 2021]
Finished job 2.
1 of 5 steps (20%) done

[Mon Feb 15 20:22:42 2021]
rule compute_universality:
    input: output/orthogroups.pickle, output/orthology_info.txt
    output: output/computed_orthogroup_features/UNI.tsv, output/computed_gene_features/UNI_genes.tsv
    jobid: 3

[Mon Feb 15 20:22:42 2021]
Finished job 3.
2 of 5 steps (40%) done

[Mon Feb 15 20:22:42 2021]
rule compute_average_copy_number:
    input: output/orthogroups.pickle
    output: output/computed_orthogroup_features/ACN.tsv, output/computed_gene_features/ACN_genes.tsv
    jobid: 4

[Mon Feb 15 20:22:42 2021]
Error in rule compute_average_copy_number:
    jobid: 4
    output: output/computed_orthogroup_features/ACN.tsv, output/computed_gene_features/ACN_genes.tsv

RuleException:
CalledProcessError in line 18 of /mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/compute_features.smk:
Command 'set -euo pipefail;  /home/lruzzant/miniconda3/envs/evol-feat/bin/python3.7 /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/scripts/tmpvjawxo4z.compute_ACN.py' returned non-zero exit status 1.
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/compute_features.smk", line 18, in __rule_compute_average_copy_number
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/log/2021-02-15T202240.871124.snakemake.log
