Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	compute_average_copy_number
	1	compute_universality
	1	merge_orthogroup_features
	1	process_orthology_table
	1	split_user_orthogroup_features
	6

[Mon Feb 15 20:41:50 2021]
rule process_orthology_table:
    input: input/Anophelinae_OGs.txt
    output: output/orthogroups.pickle, output/genes.pickle, output/orthology_info.txt
    jobid: 5

[Mon Feb 15 20:41:51 2021]
Finished job 5.
1 of 6 steps (17%) done

[Mon Feb 15 20:41:51 2021]
checkpoint split_user_orthogroup_features:
    input: input/user_features.txt
    output: output/user_orthogroup_features/
    jobid: 2
Downstream jobs will be updated after completion.

Updating job 1 (merge_orthogroup_features).
[Mon Feb 15 20:41:52 2021]
Finished job 2.
2 of 6 steps (33%) done

[Mon Feb 15 20:41:52 2021]
rule compute_universality:
    input: output/orthogroups.pickle, output/orthology_info.txt
    output: output/computed_orthogroup_features/UNI.tsv
    jobid: 3

[Mon Feb 15 20:41:52 2021]
Error in rule compute_universality:
    jobid: 3
    output: output/computed_orthogroup_features/UNI.tsv

RuleException:
CalledProcessError in line 39 of /mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/compute_features.smk:
Command 'set -euo pipefail;  /home/lruzzant/miniconda3/envs/evol-feat/bin/python3.7 /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/scripts/tmprqyl4xc0.compute_UNI.py' returned non-zero exit status 1.
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/compute_features.smk", line 39, in __rule_compute_universality
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
Removing output files of failed job compute_universality since they might be corrupted:
output/computed_orthogroup_features/UNI.tsv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/log/2021-02-15T204150.416178.snakemake.log
